time make test1
time make test2
time make test3
time make test4
time make test5
time make test6
time make test7
time make test8
time make test9
time make test10
time make test11
time make test12
time make test13
time make test14
